daemon:
  environment:
    DB_HOST: db
    DB_NAME: postgres
    DB_PASSWORD: password
    DB_PORT: "5432"
    DB_UPDATE_TIME: "60"
    DB_USER: postgres
    START_NEW_JOBS: "600"
    TOTAL_JOBS: "0"
    USER_NAME: ""
  repository:
    image: sfapi_job_daemon
    tag: ""
db:
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_USER: postgres
  persistence:
    db:
      capacity: 1Gi
      enabled: false
  repository:
    image: postgres
    tag: 14.1-alpine
