version: '3.8'
services:
  daemon:
    container_name: sfapi_job_daemon
    build:
      context: ./
    image: sfapi_job_daemon
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      USER_NAME: ${USER_NAME}
      TOTAL_JOBS: 1
      DB_UPDATE_TIME: 60
      START_NEW_JOBS: 600
    volumes:
      - ~/.superfacility:/keys/superfacility
    links:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 30
        window: 10s
  db:
    image: postgres:14.1-alpine
    command:
      [
        "postgres",
        "-c",
        "log_statement=ddl",
        "-c",
        "log_destination=stderr"
      ]
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db:
    driver: local
