apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-daemon'
  labels:
    component: daemon
    project: '{{ .Chart.Name }}'
    release: '{{ .Release.Name }}'
spec:
  selector:
    component: daemon
    release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
