apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-db'
  labels:
    component: db
    project: '{{ .Chart.Name }}'
    release: '{{ .Release.Name }}'
spec:
  selector:
    component: db
    release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
